INSERT INTO account(login, user_password, email, birth_year) VALUES ('test', 'testpass', 'test@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test1', 'test1pass', 'test1@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test2', 'test2pass', 'test2@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test3', 'test3pass', 'test3@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test4', 'test4pass', 'test4@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test5', 'test5pass', 'test5@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test6', 'test6pass', 'test6@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test7', 'test7pass', 'test7@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test8', 'test8pass', 'test8@gmail.com', 1905);
INSERT INTO account(login, user_password, email, birth_year) VALUES ('test9', 'test9pass', 'test9@gmail.com', 1905);

INSERT INTO quote(content, votes, owner) VALUES ('abc', 85, 'test1');
INSERT INTO quote(content, votes, owner) VALUES ('def!', 70, 'test5');
INSERT INTO quote(content, votes, owner) VALUES ('ghi', 80, 'test9');
INSERT INTO quote(content, votes, owner) VALUES ('jkl', 90, 'test1');
INSERT INTO quote(content, votes, owner) VALUES ('mno', 100, 'test5');
INSERT INTO quote(content, votes, owner) VALUES ('pqr', 60, 'test9');
INSERT INTO quote(content, votes, owner) VALUES ('st', 45, 'test1');
INSERT INTO quote(content, votes, owner) VALUES ('qw', 33, 'test5');
INSERT INTO quote(content, votes, owner) VALUES ('xyz', 22, 'test9');
INSERT INTO quote(content, votes, owner) VALUES ('aabbcc', 11, 'test1');
INSERT INTO quote(content, votes, owner) VALUES ('ddeeff', 1, 'test5');
INSERT INTO quote(content, votes, owner) VALUES ('gggg', 3, 'test9');
INSERT INTO quote(content, votes, owner) VALUES ('hhhhh', 5, 'test1');
INSERT INTO quote(content, votes, owner) VALUES ('iiiii', 3, 'test5');
INSERT INTO quote(content, votes, owner) VALUES ('kkkkk', 2, 'test9');
INSERT INTO quote(content, votes, owner) VALUES ('llll', 1, 'test1');
INSERT INTO quote(content, votes, owner) VALUES ('mmmmm', 78, 'test5');
INSERT INTO quote(content, votes, owner) VALUES ('nnnn', 45, 'test9');
INSERT INTO quote(content, votes, owner) VALUES ('pppppp', 12, 'test1');
INSERT INTO quote(content, votes, owner) VALUES ('qqqqqq', 31, 'test5');
INSERT INTO quote(content, votes, owner) VALUES ('rrrrrr', 13, 'test9');